### ISSUE TITLE
How to run on Video file and save output results? 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [Mayurji/Social-DIstancing-Using-Deep-Learning-and-OpenCV#1]
Hi , I am using YOLOV3 and I want to detect about 6 classes of objects and i can do it successfully. Now I want to perform distance calculation between detected objects and draw line between them on video file and save the output. can you guide me about that?

**Comment by Mayurji** [comment]
Since Video is sequence of images/frames, any thing that works on image will also work on frames of video. Since your model has detected all the objects, it captures the bounding boxes around it. So based on that, you can keep one object as reference and find distance between the referenced object and all other objects or you can change the reference randomly if required. 

To find distance between objects, you can calculate the center point of the bounding boxes while keeping referenced object's center point as constant from which you will find the distance between referenced objects center and other object's center.


You can checkout the YOLO Notebook under Advance CNN in Computer-Vision Repo on how to detect objects in real time video.
